chore: remove Go
aspect-build/rules_rollup pull request #93
Opened 2024-02-05 20:46 UTC by alexeagle

We don't have any Go sources in rules_rollup so there's no reason we should install a Go toolchain or worry about upgrading it. 'aspect configure' provides the auto-generation for bzl_library targets so we don't need Gazelle either.

2024-02-05 21:12 UTC, alexeagle commented
Note, this repo has no CI coverage for `bzl_library` targets staying up-to-date. Will address in a follow-up.

2024-02-05 21:50 UTC, gregmagolan requested changes
Hold on this until tomorrow to discuss

2024-02-06 21:23 UTC, alexeagle commented
This repo isn't currently on workflows, @gregmagolan would you approve?

2024-02-06 21:35 UTC, gregmagolan approved these changes

2024-02-06 21:35 UTC, merged